### ISSUE TITLE
[FB] Content - Ensure Actions is turned on prior to starting any exercises

### ISSUE THREAD

**Issue by WritingPanda** [CloudLabs-MOC/Github-Advanced-Security#24]
GitHub Actions is turned off by default when forking repositories. Since we are forking these repos, it is imperative that participants turn on Actions manually by going to the actions tab in each repo and turning on Actions. This will prevent issues later on in the bootcamp when participants are turning on Code Scanning and cannot get a successful CodeQL scan.

**Comment by sumitmalik51** [comment]
Added instructions and notes for all the repositry to turn it on before starting the exercise.
