### ISSUE TITLE
[FB] Content - No need for a CodeQL.yml file when using default setup

### ISSUE THREAD

**Issue by WritingPanda** [CloudLabs-MOC/Github-Advanced-Security#9]
## Feedback summary
On this line: [https://github.com/CloudLabs-MOC/Github-Advanced-Security/blob/52f1ca641813a5681a21334f9e293897fe40c088/GitHub%20Copilot%20Autofix.md?plain=1#L33](https://github.com/CloudLabs-MOC/Github-Advanced-Security/blob/52f1ca641813a5681a21334f9e293897fe40c088/GitHub%20Copilot%20Autofix.md?plain=1#L33) there is mention of using a codeql.yml file with default setup, which is not how that works. I advise to remove any mention of a codeql.yml file from any usage of default setup because the yaml file will not be used at all. It is an unnecessary step.

For advanced setup, a codeql.yaml file is necessary, but there is no need for us to go into advanced setup for this module

## Relevant links

- https://github.com/CloudLabs-MOC/Github-Advanced-Security/blob/52f1ca641813a5681a21334f9e293897fe40c088/GitHub%20Copilot%20Autofix.md?plain=1#L33

**Comment by sumitmalik51** [comment]
@Legendary-7 FYI

**Comment by anandt1-spektra** [comment]
This has been updated with the latest steps
